// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	gitnames "code.gitea.io/gitea/models/gitnames"
	mock "github.com/stretchr/testify/mock"

	pull_request_reader "code.gitea.io/gitea/routers/private/pull_request_reader"
)

// PullRequestHeaderParser is an autogenerated mock type for the pullRequestHeaderParser type
type PullRequestHeaderParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: _a0
func (_m *PullRequestHeaderParser) Parse(_a0 pull_request_reader.PullRequestHeader) (gitnames.PullRequestLinks, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 gitnames.PullRequestLinks
	var r1 error
	if rf, ok := ret.Get(0).(func(pull_request_reader.PullRequestHeader) (gitnames.PullRequestLinks, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(pull_request_reader.PullRequestHeader) gitnames.PullRequestLinks); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(gitnames.PullRequestLinks)
	}

	if rf, ok := ret.Get(1).(func(pull_request_reader.PullRequestHeader) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullRequestHeaderParser creates a new instance of PullRequestHeaderParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestHeaderParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestHeaderParser {
	mock := &PullRequestHeaderParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
