// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	repo "code.gitea.io/gitea/models/repo"
	mock "github.com/stretchr/testify/mock"
)

// RepoKeyDB is an autogenerated mock type for the repoKeyDB type
type RepoKeyDB struct {
	mock.Mock
}

// GetRepoByKey provides a mock function with given fields: ctx, key
func (_m *RepoKeyDB) GetRepoByKey(ctx context.Context, key string) (*repo.ScRepoKey, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoByKey")
	}

	var r0 *repo.ScRepoKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repo.ScRepoKey, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repo.ScRepoKey); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.ScRepoKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepoKeyDB creates a new instance of RepoKeyDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoKeyDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoKeyDB {
	mock := &RepoKeyDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
