version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.rootless
    restart: always
    volumes:
      - ./dataDocker:/var/lib/gitea
      - ./configDocker:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
