// Package generic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package generic

// Defines values for ContextEntityType.
const (
	REPOSITORY ContextEntityType = "REPOSITORY"
)

// Defines values for ContextEventCode.
const (
	CREATE ContextEventCode = "CREATE"
	DELETE ContextEventCode = "DELETE"
	UPDATE ContextEventCode = "UPDATE"
)

// Context Context
type Context struct {
	// EntityType Entity type
	EntityType ContextEntityType `json:"entity_type"`

	// EventCode Event code
	EventCode ContextEventCode `json:"event_code"`

	// EventCreateTs Event create timestamp in UTC
	EventCreateTs string `json:"event_createTs"`

	// EventId Event ID
	EventId string `json:"event_id"`

	// TenantId Tenant ID
	TenantId string `json:"tenant_id"`
}

// ContextEntityType Entity type
type ContextEntityType string

// ContextEventCode Event code
type ContextEventCode string
