// Package generic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package generic

// Metadata Metadata
type Metadata struct {
	// CorrelationMessageId Message UUID for correlation
	CorrelationMessageId *string `json:"correlation_message_id,omitempty"`

	// MessageCreateTs Message creation timestamp in UTC
	MessageCreateTs string `json:"message_create_ts"`

	// MessageId Message UUID
	MessageId string `json:"message_id"`

	// Producer Producer metadata
	Producer Producer `json:"producer"`

	// Version Message version
	Version string `json:"version"`
}

// Producer Producer metadata
type Producer struct {
	// Id Producer ID
	Id string `json:"id"`
}
