// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	xorm "xorm.io/xorm"
)

// DbEngine is an autogenerated mock type for the dbEngine type
type DbEngine struct {
	mock.Mock
}

// Exec provides a mock function with given fields: _a0
func (_m *DbEngine) Exec(_a0 ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (sql.Result, error)); ok {
		return rf(_a0...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) sql.Result); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(_a0...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *DbEngine) Find(_a0 interface{}, _a1 ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Where provides a mock function with given fields: _a0, _a1
func (_m *DbEngine) Where(_a0 interface{}, _a1 ...interface{}) *xorm.Session {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Where")
	}

	var r0 *xorm.Session
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) *xorm.Session); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xorm.Session)
		}
	}

	return r0
}

// NewDbEngine creates a new instance of DbEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbEngine {
	mock := &DbEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
