// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	protected_branch "code.gitea.io/gitea/models/git/protected_branch"
	mock "github.com/stretchr/testify/mock"

	repo "code.gitea.io/gitea/models/repo"
)

// ManagerProtectedBranchDB is an autogenerated mock type for the managerProtectedBranchDB type
type ManagerProtectedBranchDB struct {
	mock.Mock
}

// CreateProtectedBranch provides a mock function with given fields: ctx, protectedBranch
func (_m *ManagerProtectedBranchDB) CreateProtectedBranch(ctx context.Context, protectedBranch *protected_branch.ProtectedBranch) (*protected_branch.ProtectedBranch, error) {
	ret := _m.Called(ctx, protectedBranch)

	if len(ret) == 0 {
		panic("no return value specified for CreateProtectedBranch")
	}

	var r0 *protected_branch.ProtectedBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *protected_branch.ProtectedBranch) (*protected_branch.ProtectedBranch, error)); ok {
		return rf(ctx, protectedBranch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *protected_branch.ProtectedBranch) *protected_branch.ProtectedBranch); ok {
		r0 = rf(ctx, protectedBranch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protected_branch.ProtectedBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *protected_branch.ProtectedBranch) error); ok {
		r1 = rf(ctx, protectedBranch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProtectedBranch provides a mock function with given fields: ctx, repoID, id
func (_m *ManagerProtectedBranchDB) DeleteProtectedBranch(ctx context.Context, repoID int64, id int64) error {
	ret := _m.Called(ctx, repoID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProtectedBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, repoID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindRepoProtectedBranchRules provides a mock function with given fields: ctx, repoID
func (_m *ManagerProtectedBranchDB) FindRepoProtectedBranchRules(ctx context.Context, repoID int64) (protected_branch.ProtectedBranchRules, error) {
	ret := _m.Called(ctx, repoID)

	if len(ret) == 0 {
		panic("no return value specified for FindRepoProtectedBranchRules")
	}

	var r0 protected_branch.ProtectedBranchRules
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (protected_branch.ProtectedBranchRules, error)); ok {
		return rf(ctx, repoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) protected_branch.ProtectedBranchRules); ok {
		r0 = rf(ctx, repoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protected_branch.ProtectedBranchRules)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, repoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProtectedBranchRuleByID provides a mock function with given fields: ctx, repoID, ruleID
func (_m *ManagerProtectedBranchDB) GetProtectedBranchRuleByID(ctx context.Context, repoID int64, ruleID int64) (*protected_branch.ProtectedBranch, error) {
	ret := _m.Called(ctx, repoID, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for GetProtectedBranchRuleByID")
	}

	var r0 *protected_branch.ProtectedBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*protected_branch.ProtectedBranch, error)); ok {
		return rf(ctx, repoID, ruleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *protected_branch.ProtectedBranch); ok {
		r0 = rf(ctx, repoID, ruleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protected_branch.ProtectedBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, repoID, ruleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProtectedBranchRuleByName provides a mock function with given fields: ctx, repoID, ruleName
func (_m *ManagerProtectedBranchDB) GetProtectedBranchRuleByName(ctx context.Context, repoID int64, ruleName string) (*protected_branch.ProtectedBranch, error) {
	ret := _m.Called(ctx, repoID, ruleName)

	if len(ret) == 0 {
		panic("no return value specified for GetProtectedBranchRuleByName")
	}

	var r0 *protected_branch.ProtectedBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*protected_branch.ProtectedBranch, error)); ok {
		return rf(ctx, repoID, ruleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *protected_branch.ProtectedBranch); ok {
		r0 = rf(ctx, repoID, ruleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protected_branch.ProtectedBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, repoID, ruleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProtectBranch provides a mock function with given fields: ctx, _a1, protectedBranch
func (_m *ManagerProtectedBranchDB) UpdateProtectBranch(ctx context.Context, _a1 *repo.Repository, protectedBranch *protected_branch.ProtectedBranch) (*protected_branch.ProtectedBranch, error) {
	ret := _m.Called(ctx, _a1, protectedBranch)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProtectBranch")
	}

	var r0 *protected_branch.ProtectedBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.Repository, *protected_branch.ProtectedBranch) (*protected_branch.ProtectedBranch, error)); ok {
		return rf(ctx, _a1, protectedBranch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repo.Repository, *protected_branch.ProtectedBranch) *protected_branch.ProtectedBranch); ok {
		r0 = rf(ctx, _a1, protectedBranch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protected_branch.ProtectedBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repo.Repository, *protected_branch.ProtectedBranch) error); ok {
		r1 = rf(ctx, _a1, protectedBranch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertProtectBranch provides a mock function with given fields: ctx, _a1, protectBranch, opts
func (_m *ManagerProtectedBranchDB) UpsertProtectBranch(ctx context.Context, _a1 *repo.Repository, protectBranch *protected_branch.ProtectedBranch, opts protected_branch.WhitelistOptions) error {
	ret := _m.Called(ctx, _a1, protectBranch, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpsertProtectBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.Repository, *protected_branch.ProtectedBranch, protected_branch.WhitelistOptions) error); ok {
		r0 = rf(ctx, _a1, protectBranch, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewManagerProtectedBranchDB creates a new instance of ManagerProtectedBranchDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagerProtectedBranchDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagerProtectedBranchDB {
	mock := &ManagerProtectedBranchDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
