// Package events provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package events

// Defines values for Action.
const (
	Create Action = "create"
	Delete Action = "delete"
	Update Action = "update"
)

// Defines values for EventType.
const (
	Node    EventType = "node"
	Nothing EventType = "nothing"
	Other   EventType = "other"
	System  EventType = "system"
	User    EventType = "user"
)

// Action Action performed on the event, e.g. create, update, delete
type Action string

// CreateRepositoryEvent Create repository event
type CreateRepositoryEvent struct {
	// Action Action performed on the event, e.g. create, update, delete
	Action Action `json:"action"`

	// Id Event id
	Id string `json:"id"`

	// Issuer Issuer of the event
	Issuer string `json:"issuer"`

	// ProjectInfo Information about the project
	ProjectInfo ProjectInfo `json:"project-info"`

	// Properties Properties of the event
	Properties []Property `json:"properties"`

	// TenantId Tenant id
	TenantId string `json:"tenant-id"`

	// Timestamp When the event was created
	Timestamp int `json:"timestamp"`

	// Type Type of the event
	Type EventType `json:"type"`

	// UserInfo Information about the user who performed the action
	UserInfo UserInfo `json:"user-info"`

	// Version Version of contract
	Version string `json:"version"`
}

// EventType Type of the event
type EventType string

// ProjectInfo Information about the project
type ProjectInfo struct {
	// ProjectId Project id
	ProjectId string `json:"project-id"`

	// ProjectKey Project key
	ProjectKey *string `json:"project-key,omitempty"`

	// ProjectName Project name
	ProjectName *string `json:"project-name,omitempty"`

	// Tenant Project tenant
	Tenant *string `json:"tenant,omitempty"`
}

// Property Property of the event
type Property struct {
	// Name Property name
	Name string `json:"name"`

	// Value Property value
	Value string `json:"value"`
}

// UserInfo Information about the user who performed the action
type UserInfo struct {
	// UserId User id
	UserId string `json:"user-id"`
}
