// Package events provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package events

import (
	externalRef0 "code.gitea.io/gitea/models/events/v2/generic"
)

// AdditionalProperties Additional properties
type AdditionalProperties map[string]string

// CreateRepositoryEvent Create repository event
type CreateRepositoryEvent struct {
	// Context Context
	Context externalRef0.Context `json:"context"`

	// Metadata Metadata
	Metadata externalRef0.Metadata `json:"metadata"`
	Payload  Payload               `json:"payload"`
}

// InitiatorUser Initiator user
type InitiatorUser struct {
	// Id User id
	Id string `json:"id"`
}

// Payload defines model for Payload.
type Payload struct {
	// AdditionalProperties Additional properties
	AdditionalProperties *AdditionalProperties `json:"additional_properties,omitempty"`

	// InitiatorUser Initiator user
	InitiatorUser InitiatorUser `json:"initiator_user"`

	// RepositoryInfo Repository info
	RepositoryInfo RepositoryInfo `json:"repository_info"`
}

// RepositoryInfo Repository info
type RepositoryInfo struct {
	// ProjectName Project name
	ProjectName string `json:"project_name"`

	// RepositoryId Repository id
	RepositoryId string `json:"repository_id"`

	// RepositoryName Repository name
	RepositoryName string `json:"repository_name"`

	// TenantName Tenant name
	TenantName string `json:"tenant_name"`
}
